name = "soiv-studio-website"
compatibility_date = "2023-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"
output_dir = "dist"

# Cloudflare Pages 설정
pages_build_output_dir = "dist"

[env.production]
name = "soiv-studio-website"